import sqlite3
conn = sqlite3.connect("dictionary.db")
c = conn.cursor()

#c.execute("create table slang(key text, data text)")

abbreviations_list = {
"ur":"your",
"u're":"you're",
"r":"are",

"youre": "you're",
"theyre":"they're",
"im":"i'm",
"hes":"he's",
"shes":"she's",

"Srsly":"seriously",

"cuz":"because",
"coz":"because",
"cos":"because",
"cause":"because",
"cause":"because",
"yea":"yes",
"ye":"yes",
"yh":"yes",


"plz":"please",
"pls":"please",
"plox":"please",
"pl0x":"please",

"ikr":"i do know",
"fb":"facebook",

"xd":"[Happy face]",
"xp":"[sticking out tongue face]",
"x)":"[Happy face]",
"x(":"[unhappy face",
":p":"[sticking out tongue face]",
":d":"[happy face]",
":)":"[smiley face]",
":(":"[unhappy face]",
";p":"[winking sticking out tongue face]",
";d":"[winking happy face]",
";)":"[winking face]",
";(":"[winking unhappy face]",


"obvs":"obvious",
"aaf": "as a friend",
"adad": "another day another dollar",
"adih": "another day in hell",
"adip": "another day in paradise",
"aeap": "as early as possible",
"afaicr": "as far as i can recall",
"afaics": "as far as i can see",
"afaict": "as far as i can tell",
"afaik": "as far as i know",
"afair": "as far as i remember",
"afap": "as far as possible",
"afk": "away from keyboard",
"alol": "actually laughing out loud",
"asap": "as soon as possible",
"asl": "age, sex, location",
"a/s/l": "age/sex/location",
"aslp": "age, sex, location, picture",
"a/s/l/p": "age, sex, location, picture",
"ateotd": "at the end of the day",
"atb": "all the best",
"atm": "at the moment",
"awol": "absent without official leave",
"b2b": "business to business",
"b2c": "business to customer",
"b4": "before",
"bbiab": "be back in a bit",
"bbs": "be back soon",
"bcnu": "be seein' you",
"bff": "best friends forever",
"bfn": "bye for now",
"brb": "be right back",
"bsod": "blue screen of death",
"btdt": "been there done that",
"btw": "by the way",
"cmiiw": "correct me if i'm wrong.",
"cu": "see you",
"cya": "see ya or cover your ass",
"dftt": "don't feed the trolls",
"dftba": "don't forget to be awesome",
"dgaf": "don't give a ****",
"diaf": "die in a fire",
"dilligaf": "does it look like i give a flip",
"d/l": "download",
"dnd": "do not disturb",
"doa": "dead on arrival",
"eof": "end of file",
"eom": "end of message",
"eol": "end of life",
"eq": "everquest",
"esad": "eat **** and die",
"eta": "estimated time of arrival",
"f9": "fine",
"faq": "frequently asked question(s)",
"ffs": "for ****'s sake",
"fmcdh": "from my cold dead hands",
"fml": "**** my life.",
"foad": "**** off and die",
"foaf": "friend of a friend",
"ftfy": "fixed that for you",
"ftl": "for the loss",
"ftw": "for the win",
"ftw": "**** the what",
"fu": "**** you",
"fubar": "****ed up beyond all recognition",
"fud": "fear, uncertainty and doubt ",
"fwiw": "for what it's worth",
"fyi": "for your information",
"gbtw": "get back to work",
"gf": "great/good fight",
"gfu": "good for you",
"gfy": "go **** yourself",
"gg": "good game, used at or near the conclusion of a gaming match",
"ggs": "good games",
"gj": "good job",
"gl": "good luck, used before commencing a game",
"gmta": "great minds think alike",
"gratz": "congratulations",
"gtfo": "get the **** out",
"gtg": "got to go",
"g2g": "got to go",
"gr": "good race",
"hand": "have a nice day",
"handle": "nickname",
"hf": "have fun",
"haxor": "hacker",
"hth": "hope that helps",
"ianal": "i am not a lawyer",
"ibtl": "in before the lock",
"idk": "i don't know",
"iht": "i had to",
"iono": "i don't know",
"iirc": "if i remember correctly",
"iiuc": "if i understand correctly",
"ily": "i love you",
"imo": "in my opinion",
"imho": "in my honest opinion",
"iow": "in other words",
"irc": "internet relay chat",
"irl": "in real life",
"istm": "it seems to me",
"itym": "i think you mean",
"iwsn": "i want sex now",
"iykwim": "if you know what i mean",
"izi": "easy",
"jas": "just a sec",
"jftr": "just for the record",
"jk": "just kidding",
"j/k": "just kidding",
"k": "ok",
"kk": "ok",
"kos": "kill on sight",
"kthx": "ok, thanks",
"kthxbye": "ok, thanks, goodbye",
"l8r": "later.",
"lamer": "lame person",
"lfg": "looking for group",
"lfm": "looking for more",
"lmao": "laughing my ass off",
"lmbo": "laughing my butt off",
"lmfao": "laughing my ****ing ass off",
"lmgtfy": "let me google that for you",
"lmirl": "let's meet in real life",
"lmk": "let me know",
"lol": "laughing out loud",
"ltns": "long time no see",
"lulz": "laughing out loud",
"lurker": "someone who frequents a community or group without participating in discussions",
"lylab": "love you like a brother",
"lylas": "love you like a sister",
"mfw": "my face when",
"mrw": "my reaction when",
"mmo": "massive multi-player online game",
"mmorpg": "massive multiplayer online role playing game",
"motd": "message of the day",
"mtfbwy": "may the force be with you",
"myob": "mind your own business",
"m8": "mate",
"n1": "nice one",
"ne1": "anyone",
"newbie": "newcomer",
"newb": "newcomer",
"n00b": "newcomer",
"noob": "newcomer",
"noob": "newcomer",
"ngl": "not gonna lie",
"nifoc": "naked in front of computer",
"np": "no problem",
"ns": "nice shot",
"nsoh": "no sense of humor",
"nsfw": "not safe for work",
"nvm": "nevermind",
"nvmd": "nevermind",
"nm": "nevermind",
"n/m": "nevermind",
"orly": "oh really",
"oic": "oh, i see",
"ofn": "old freaking news",
"omg": "oh my god",
"omfg": "oh my ****ing god",
"omgwtf": "oh my god what the ****",
"omw": "on my way ",
"onoz": "oh, no",
"op": "original poster",
"os": "operating system",
"ot": "off topic",
"otb": "off to bed",
"otoh": "on the other hand",
"otp": "on the phone ",
"p2p": "peer to peer",
"paw": "parents are watching",
"pebkac": "problem exists between keyboard and chair",
"pita": "pain in the ass",
"plmk": "please let me know",
"pm": "private message",
"pmsl": "pissing myself laughing",
"pos": "parent over shoulder.",
"pots": "plain old telephone service",
"pov": "point of view",
"pl": "powerleveling",
"ppl": "people",
"ptkfgs": "punch the keys for god's sake",
"pw": "persistent world",
"pwned": "owned",
"qft": "quoted for truthiness",
"qwp": "quit whining, please",
"rehi": "hello again",
"rl": "real life",
"rms": "ride me sideways",
"rofl": "rolling on floor laughing",
"roflmao": "rolling on floor laughing my ass off",
"roflmaowpimp": "rolling on floor laughing my ass off while peeing in my pants",

"roflol": "rolling on the floor laughing out loud",
"rotflol": "rolling on the floor laughing out loud",
"rsn": "real soon now",
"rtfb": "read the ****ing binary",
"rtfs": "read the ****ing source",
"rtfm": "read the ****ing manual",
"rtm": "read the manual or reboot the machine",
"scnr": "sorry, could not resist",
"sfw": "safe for work",
"sk8": "skate",
"sk8r": "skater",
"sk8er": "skater",

"smiley": "emoticon",
"smh": "shaking my head",
"sohf": "sense of humor failure",
"sos": "there is someone watching over my shoulder",
"stahp ": "stop",
"stfu": "shut the **** up",
"stfw": "search the ****ing web",
"tanstaafl": "there ain't no such thing as a free lunch",
"tbf": "time between failures",
"tbh": "to be honest",
"tfw": "that feel when",
"tg": "that's great",
"tgif": "thank god it's friday",
"thx": "thanks",
"thnx": "thanks",
"tnx": "thanks",
"tx": "thanks",
"tia": "thanks in advance",
"til": "today i learned",
"timwtk": "this inquiring mind wants to know",
"tinc": "there is no cabal, a term discouraging conspiracy theories",
"tins": "there is no spoon",
"tl;dr": "too long; didn't read",
"tldr": "too long; didn't read",
"tmi": "too much information",
"toobs": "internet",
"tos": "terms of service",
"ttbomk": "to the best of my knowledge",
"ttfn": "ta ta for now",
"ttyl": "talk to you later ",
"ttul": "talk to you later",
"t2ul": "talk to you later",
"t2yl": "talk to you later",
"ttyn": "talk to you never",
"ttys": "talk to you soon",
"tweedler": "geek",
"ty": "thank you",
"tyt": "take your time",
"tyvm": "thank you very much",
"u": "you",
"utfse": "use the ****ing search engine",
"ugo": "you got owned",
"urs": "you really suck",
"w00t": "first two express exuberance",
"woot": "we own the other team",
"w/": "with",
"w/o": "without",
"wb": "welcome back",
"wbu": "what (a)bout you",
"w/e": "whatever",
"w/e": "weekend",
"wrt": "with respect to",
"wtb": "want to buy",
"wtf": "what the ****",
"wtg": "way to go",
"wth": "what the hell",
"wts": "want to sell",
"wtt": "want to trade",
"wug": "what you got",
"wubu2": "what have you been up to",
"wuu2": "what are you up to",
"wysiwyg": "what you see is what you get",
"w8": "wait",
"yagni": "you ain't gonna need it.",
"yagtoh": "you are going to own him.",
"ygm": "you've got mail.",
"yhbt": "you have been trolled.",
"yec": "young earth creationism",
"ykw": "you know what",
"ymmv": "your mileage may vary.",
"yolo": "you only live once.",
"yoyo": "you're on your own.",
"ytmnd": "you're the man now, dog",
"yw": "you're welcome.",
"zomg": "oh my god!"
}

for i in abbreviations_list:
	j = abbreviations_list.get(i)
	c.execute("""insert into slang values (?,?)""",(i,j,))

#c.execute("CREATE INDEX sindex ON slang (key)")
conn.commit()
c.close()